from typing import Any, Dict, List, Optional

class MethodPy:
    @property
    def name(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def http_method(self) -> str: ...
    @property
    def http_path(self) -> str: ...
    @property
    def param_names(self) -> List[str]: ...

class ToolSchemaPy:
    @property
    def tool_id(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def base_url(self) -> str: ...
    @property
    def methods(self) -> List[MethodPy]: ...
    
    def call_blocking(
        self,
        method_name: str,
        params: Dict[str, Any],
        auth: Optional[Dict[str, Any]] = None
    ) -> str: ...

class McpServerHandle:
    def stop(self) -> None: ...
    def port(self) -> int: ...

def parse_openapi_url(url: str) -> ToolSchemaPy: ...
def parse_openapi_str(spec: str) -> ToolSchemaPy: ...
def infer_from_html(url: str, html: str) -> ToolSchemaPy: ...
def schema_from_json(json: str) -> ToolSchemaPy: ...
def schema_to_json(schema: ToolSchemaPy) -> str: ...
def start_mcp_server(schema: ToolSchemaPy, port: int) -> McpServerHandle: ...
